apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 842062273569.dkr.ecr.us-east-1.amazonaws.com/frontend:0d590b54d7a5a2d2260f720b705fc950343227d2
          ports:
            - containerPort: 3000
