apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 842062273569.dkr.ecr.us-east-1.amazonaws.com/frontend:c0e16d9ddb0afe7c00b8428f1a76bfa3075cf4bc
          ports:
            - containerPort: 3000
