apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 842062273569.dkr.ecr.us-east-1.amazonaws.com/backend:68edf3910e14ba333d5ef4859ede1bd8b1c35701
          ports:
            - containerPort: 5000
